import "./global.css";

export const metadata = {
  title: "My App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}